name: liquid_glass_effect
description: "A flutter package to create a liquid glass effect ui."
version: 1.0.1
homepage: https://github.com/subhashDev11/liquid_glass_effect.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

screenshots:
  - description: 'Liquid glass ui example with weather app.'
    path: screenshots/scrs1.jpg
  - description: 'Liquid glass ui example with weather app.'
    path: screenshots/scrs2.jpg

topics:
  - liquid-glass-ui
  - liquid-glass-effect
  - liquid-glass-theme
  - liquid-glass-card
  - ios26-like-liquid-glass-ui